language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gsapkar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gsapkar/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-goce"
  env: "DockerReactGoce-env"
  bucket_name: "elasticbeanstalk-eu-central-1-202873920067"
  bucket_path: "docker-react-goce"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
